cargo-features = ["edition"]

[package]
edition = "2018"
name = "zerodmg"
version = "0.1.0"
authors = ["Jeremy Banks <_@jeremy.ca>"]

[dependencies]
futures = "*"
hyper = "*"
tokio = "*"
rand = "*"
image = "*"
