cargo-features = ["edition"]

[package]
edition = "2018"
name = "zerodmg-utils"
version = "0.1.4"
license = "MIT"
authors = ["Jeremy Banks <_@jeremy.ca>"]
repository = "https://github.com/jeremyBanks/0dmg"
description = "pieces of a naive incomplete broken game boy emulator"
readme = "../README.md"

[dependencies]
image = "0.19.0"
