cargo-features = ["edition"]

[package]
edition = "2018"
name = "zerodmg-emulator"
version = "0.1.0"
authors = ["Jeremy Banks <_@jeremy.ca>"]

[dependencies]
zerodmg-utils = { version = "0.1.0", path = "../zerodmg-utils" }
image = "0.19.0"
